#!/usr/bin/env node
// Copies ONLY the OpenMoji colour SVGs that the emoji cards use into public/openmoji/ (optimised with SVGO), and
// writes src/openmoji.ts (emoji → hexcode). Self-hosted: the app never loads images from another origin; the
// service worker precaches public/ (globPatterns include svg), so the pictures work offline.
// Source of the emoji: EMOJI_SEED_CARDS in apps-script/Schema.gs (front = the emoji) + scripts/openmoji-extra.json.
// Run: npm run openmoji
import { readFileSync, writeFileSync, mkdirSync, readdirSync, rmSync, statSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { optimize } from 'svgo';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = join(root, 'node_modules/openmoji');
const outDir = join(root, 'public/openmoji');
const version = JSON.parse(readFileSync(join(pkg, 'package.json'), 'utf8')).version;

const schema = readFileSync(join(root, 'apps-script/Schema.gs'), 'utf8');
const block = schema.slice(schema.indexOf('var EMOJI_SEED_CARDS'), schema.indexOf('];', schema.indexOf('var EMOJI_SEED_CARDS')));
const emojis = [...block.matchAll(/'E-\d+\|([^|]+)\|/g)].map((m) => m[1]);
// Emoji cards added later (not seeded) are listed in scripts/openmoji-extra.json (groups of emoji; an OpenMoji-only
// picture — no Unicode emoji, hexcode E000–EFFF, e.g. "E0C0" — is listed by its hexcode and its card front is
// "openmoji:E0C0"). Add them there, then run npm run openmoji.
const extraFile = JSON.parse(readFileSync(join(root, 'scripts/openmoji-extra.json'), 'utf8'));
const EXTRA = Object.entries(extraFile).filter(([k]) => !k.startsWith('_')).flatMap(([, list]) => list);
const isHex = (e) => /^E[0-9A-F]{3}(-[0-9A-F]+)*$/i.test(e);
for (const e of EXTRA) if (!emojis.includes(e)) emojis.push(e);

const strip = (s) => s.replace(/️/g, '');
const data = JSON.parse(readFileSync(join(pkg, 'data/openmoji.json'), 'utf8'));
const exact = new Map(data.map((d) => [d.emoji, d.hexcode]));
const loose = new Map(data.map((d) => [strip(d.emoji), d.hexcode]));

const map = {};
const missing = [];
for (const e of emojis) {
  if (isHex(e)) {
    // OpenMoji-only: the SVG must exist in the package (not every hexcode does, e.g. E1DB in 17.0.0).
    const hex = e.toUpperCase();
    if (existsSync(join(pkg, 'color/svg', `${hex}.svg`))) map[`openmoji:${hex}`] = hex;
    else missing.push(e);
    continue;
  }
  const hex = exact.get(e) ?? loose.get(strip(e));
  if (hex) map[e] = hex;
  else missing.push(e);
}

mkdirSync(outDir, { recursive: true });
for (const f of readdirSync(outDir)) if (f.endsWith('.svg')) rmSync(join(outDir, f)); // only what is used
let bytes = 0;
const used = [...new Set(Object.values(map))];
for (const hex of used) {
  const src = readFileSync(join(pkg, 'color/svg', `${hex}.svg`), 'utf8');
  const { data: svg } = optimize(src, { multipass: true, plugins: ['preset-default'] });
  writeFileSync(join(outDir, `${hex}.svg`), svg);
  bytes += Buffer.byteLength(svg);
}
writeFileSync(
  join(outDir, 'LICENSE.txt'),
  `These images are from OpenMoji ${version} (https://openmoji.org/), the open-source emoji and icon project.\n` +
    'License: CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/).\n' +
    'Only the files the app uses are included, losslessly optimised with SVGO (no visual change).\n'
);

const lines = Object.entries(map).map(([e, hex]) => `  ${JSON.stringify(e)}: '${hex}',`);
writeFileSync(
  join(root, 'src/openmoji.ts'),
  `// GENERATED by scripts/openmoji.mjs (npm run openmoji) from OpenMoji ${version} — do not edit by hand.\n` +
    '// Emoji (as written in the sheet) → OpenMoji hexcode; the SVG is self-hosted at public/openmoji/<hexcode>.svg.\n' +
    `export const OPENMOJI: Record<string, string> = {\n${lines.join('\n')}\n};\n\n` +
    '/**\n * The OpenMoji hexcode for a card front that is one emoji (with or without the FE0F selector) or an OpenMoji-only\n' +
    ' * picture written as "openmoji:E0C0", else null.\n */\n' +
    'export function openmojiFor(text: string): string | null {\n' +
    "  const t = text.trim();\n" +
    "  if (/^openmoji:/i.test(t)) return OPENMOJI['openmoji:' + t.slice(9).toUpperCase()] ?? null;\n" +
    "  return OPENMOJI[t] ?? OPENMOJI[t.replace(/\\uFE0F/g, '')] ?? OPENMOJI[t + '\\uFE0F'] ?? null;\n" +
    '}\n'
);

console.log(`OpenMoji ${version}: ${emojis.length} emoji cards → ${used.length} images, ${(bytes / 1024).toFixed(1)} KB total`);
console.log(missing.length ? `No OpenMoji match: ${missing.join(' ')}` : 'Every emoji has an OpenMoji match.');
